
------

# **Numpy Practice**

------



In [1]:
# import numpy
import numpy as np

In [2]:
# create an empty array
empty = np.empty((3,4))
empty

array([[1.08295818e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 3.69776220e-062, 6.50836525e-091,
        4.27969691e-037],
       [3.57099629e-062, 1.26664631e-071, 3.99910963e+252,
        2.49030926e+180]])

In [4]:
# create an array of specified number
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
# create an array of specified range even numbers
np.arange(0,26,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [8]:
# create an array of specified range odd numbers
np.arange(1,39,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37])

In [9]:
# create an array of specified number difference
np.arange(0,23,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [10]:
# linear trend numbers
np.linspace(0,20,num=20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [12]:
# explicitly call data type of array
np.ones(6,dtype="float64")

array([1., 1., 1., 1., 1., 1.])

In [14]:
# sorting an array

a = np.array([6,8,1,3,5,9,10,2,4,7,6])

sorted_array = np.sort(a)
sorted_array

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

In [18]:
# concatenation of arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# concatenating 2 different arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.concatenate((a,b),axis=1)

c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [19]:
# concatenating 2 different arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

c = np.concatenate((a,b),axis=0)

c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# reshaping an array
a = np.array([[[0,1,2,3]],
              [[4,5,6,7]],
              [[8,9,10,11]]])

print(f"Before Reshape: {a.shape}")
arr = a.reshape(6,2)
print(f"After Reshape: {arr.shape}")


Before Reshape: (3, 1, 4)
After Reshape: (6, 2)


In [22]:
# indexing and slicing
a = np.array([1,2,3,4,5,6,6,7,8,9,10])

a[1:5]

array([2, 3, 4, 5])

In [24]:
a[-3:]

array([ 8,  9, 10])

In [36]:
# indexing and slicing
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [38]:
a[-1:]

array([[ 9, 10, 11, 12]])

In [39]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [43]:
print(a[a < 5])

[1 2 3 4]


In [41]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [42]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


------