

--------

# **Numpy Indexing and Slicing**

--------

In [1]:
# import numpy library
import numpy as np

In [2]:
# create an array
a = np.array([1,2,3,4,5])  

In [4]:
a[0] # to view first element

1

In [3]:
a[-1] # to view last element

5

In [6]:
b = np.arange(0,12,2)
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [10]:
a[(a<5)|(a>7)]

array([1, 2, 3, 4])

In [14]:
# vstack

a = np.array([1,2,3,4,5]) 
b = np.array([6,7,8,9,10])
c = np.vstack((a,b))
c 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
# hstack

a = np.array([1,2,3,4,5]) 
b = np.array([6,7,8,9,10])
c = np.hstack((a,b))
c 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---------