

-----------

# ***`NumPy for Data Science`***

## **Introduction to NumPy**
- **What is NumPy?**
  - NumPy (Numerical Python) is a fundamental library for numerical computing in Python.
  - It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.

- **Why Use NumPy?**
  - Efficient storage and manipulation of numerical data.
  - High performance for array operations due to its implementation in C.
  - Essential for scientific computing and is the foundation for many libraries like Pandas, SciPy, and Matplotlib.

## **Basics of NumPy**

### **Installation**
```bash
pip install numpy
```

### **Importing NumPy**
```python
import numpy as np
```

### **Creating Arrays**
- **1D Array**:
  ```python
  arr1d = np.array([1, 2, 3, 4])
  ```
  
- **2D Array** (Matrix):
  ```python
  arr2d = np.array([[1, 2, 3], [4, 5, 6]])
  ```

- **Special Arrays**:
  - Zeros: `np.zeros((2, 3))`
  - Ones: `np.ones((2, 3))`
  - Empty: `np.empty((2, 3))`
  - Identity Matrix: `np.eye(3)`

### **Array Attributes**
- **Shape**: `arr.shape` (returns a tuple representing the dimensions)
- **Data Type**: `arr.dtype` (returns the data type of the array elements)
- **Number of Dimensions**: `arr.ndim`

## **Array Operations**

### **Indexing and Slicing**
- Accessing elements: `arr[0]` (first element), `arr[1, 2]` (element at row 1, column 2)
- Slicing: `arr[0:2]` (first two elements), `arr[:, 1]` (second column of a 2D array)

### **Mathematical Operations**
- **Element-wise operations**:
  ```python
  arr + 2
  arr * 3
  ```

- **Statistical functions**:
  - Sum: `np.sum(arr)`
  - Mean: `np.mean(arr)`
  - Standard Deviation: `np.std(arr)`

### **Broadcasting**
- Allows operations on arrays of different shapes.
- Example:
  ```python
  arr = np.array([[1, 2, 3], [4, 5, 6]])
  arr + 1  # Adds 1 to each element
  ```

## **Advanced Features**

### **Linear Algebra**
- Solving linear equations: `np.linalg.solve(A, b)`
- Matrix multiplication: `np.dot(A, B)`

### **Random Number Generation**
- Random values: `np.random.rand(3, 2)` (3x2 array of uniform random values)
- Normal distribution: `np.random.randn(5)` (5 values from a standard normal distribution)

### **Reshaping Arrays**
- Changing the shape of an array: `arr.reshape(new_shape)`
- Flattening an array: `arr.flatten()`

## **Integration with Other Libraries**
- **Pandas**: NumPy arrays are used as the underlying data structure.
- **Matplotlib**: NumPy arrays are often used for plotting data.

## **Conclusion**
- NumPy is a powerful tool for data manipulation and numerical computations, essential for any data science project.
- Mastering its features can significantly enhance your ability to analyze and visualize data effectively.

## **Further Learning**
- Official NumPy Documentation: [NumPy Docs](https://numpy.org/doc/stable/)
- Explore additional functionalities like masked arrays, structured arrays, and advanced indexing techniques.

---

Feel free to ask if you need more details on any specific topic or concept!

------------



### **Let's Practice**

In [1]:
# import numpy library

import numpy as np

In [7]:
# create an array

a1 = np.array([1,2,3,4,5])
print(a1)

type(a1)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# create a 2D array

a2 = np.array([[1,2,3],[4,5,6]])

In [10]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [14]:
np.mean(a1)

5.5

In [15]:
np.median(a1)

5.5

In [16]:
np.std(a1)

2.8722813232690143

In [17]:
np.min(a1)

1

In [18]:
np.max(a1)

10

In [19]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [20]:
np.exp(a1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [21]:
np.log10(a1)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [22]:
# create an array of zeros with 2 rows and 3 columns
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros((2,3,4)) # 3D array with 2 rows, 3 columns and 4 depth

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
np.ones((4,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [30]:
np.random.randint(1,10000,(3,4,5))

array([[[2694, 6005, 5604, 2740, 8223],
        [ 762, 1820, 2872,  261, 6078],
        [3072,  338, 9843, 8427,  964],
        [3957, 3081, 7993, 7017, 7465]],

       [[9726, 5633, 5313, 8638, 7050],
        [4103, 6225, 2384, 3966, 6512],
        [2420, 8079, 3378, 5454, 5397],
        [2158,  879, 1384, 4200, 5888]],

       [[9147,  216, 5357, 4194, 4735],
        [1724, 6803, 6529, 3139,  988],
        [6686, 8510, 5451, 6323, 9436],
        [7143, 4497, 7992, 7905, 2191]]])

In [35]:
a= np.random.randn(1,10)

In [36]:
a.shape

(1, 10)

In [37]:
a.size

10

In [38]:
a.ndim

2

In [46]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[3,2,1]])

In [47]:
a1 + a2

array([[ 8, 10, 12],
       [ 7,  7,  7]])

In [51]:
np.dot(a2, a1.T) # dot product of a2 and transpose of a1 

array([[ 50, 122],
       [ 10,  28]])

In [52]:
a1 = np.random.randint(1,100,(3,3))
a2 = np.random.randint(1,100,(3,4))

In [53]:
np.dot(a1,a2)

array([[18429, 14808, 16104,  6435],
       [19860, 15452, 17356,  7276],
       [ 9465,  6863,  8747,  2146]])

----